#application
app:
  environment: dev
  http_port: 4000
#graceful shutdown
graceful_shutdown:
 enabled: true
 timeout: 10 # second
#db
mongodb:
 host: mongodb://localhost:27017
 database: rest_api_development

# log
log:
 level: info
 filepath: log/rest_api.log
 rotation: true
 json_format: true

swagger:
 host: "localhost:3030"
 version: v1
 base_path: /
